### PR TITLE
add ability to switch between screen and page views

### PR DESCRIPTION
**Pull request by tarciosaraiva**
Hopefully this will address https://github.com/ScreamZ/vue-analytics/issues/13

### CODE REVIEW

**Comment by ScreamZ** [comment]
Thanks you very much for your contribution.

I'll give a deep look on it at lunchbreak. :)

Regards

**Comment by tarciosaraiva** [comment]
No problem. By the way, think would be a good idea to setup some testing automation. You can do that easily with Circle CI (my preferred option these days) but it's up to you

**Comment by ScreamZ** [comment]
Of course i'll, didn't took time for it because it was a little lib at first :p But now it has growth a bit, i'll think about it :)

**Comment by ScreamZ** [comment]
@tarciosaraiva I'm real noob with circleCI

```YAML
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
```

Looks good to me, do you confirm ?

**EDIT :** 

```
yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://npm.in.chaitin.com/babel-preset-stage-2/-/babel-preset-stage-2-6.22.0.tgz: getaddrinfo ENOTFOUND npm.in.chaitin.com npm.in.chaitin.com:80".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/repo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
```

Are you sure the dependencies are ok ?

**Comment by tarciosaraiva** [comment]
The file looks OK. The fact that it failed is probably related to a network issue at the time of the build. Have you tried running it again?

**Comment by tarciosaraiva** [comment]
OK looks like there was a problem with `yarn.lock` - some dependency pointing to an older file. Fixed now.

**Comment by ScreamZ** [comment]
Nice it's working now :) Thanks you

**Pull request merged**
